project_id = "rhzmhiknbcipucfvgkok"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.split-payslips]
    verify_jwt = true
