// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/list-employees.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^4.5.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "\u05DC\u05D0 \u05DE\u05D7\u05D5\u05D1\u05E8 \u2014 \u05D9\u05E9 \u05DC\u05D4\u05EA\u05D7\u05D1\u05E8 \u05DC\u05D7\u05E9\u05D1\u05D5\u05DF \u05EA\u05E4\u05E2\u05D5\u05DC 360 \u05DB\u05D3\u05D9 \u05DC\u05D4\u05E9\u05EA\u05DE\u05E9 \u05D1\u05DB\u05DC\u05D9 \u05D6\u05D4." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-employees.ts
var list_employees_default = defineTool({
  name: "list_employees",
  title: "List employees",
  description: "List employees the signed-in user may see, optionally filtered by name/code search, status or department.",
  inputSchema: {
    search: z.string().optional().describe("Free text matched against full name or employee code."),
    status: z.enum(["active", "inactive", "offboarding"]).optional().describe("Employee status filter."),
    department: z.string().optional().describe("Exact department name."),
    limit: z.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, department, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("employees").select(
      "id, employee_code, full_name, email, phone, department, role, status, start_date, end_date, vacation_balance, sick_balance"
    ).order("full_name", { ascending: true }).limit(take);
    if (status) query = query.eq("status", status);
    if (department) query = query.eq("department", department);
    if (search?.trim()) {
      const term = `%${search.trim()}%`;
      query = query.or(`full_name.ilike.${term},employee_code.ilike.${term},email.ilike.${term}`);
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, employees: data ?? [] });
  }
});

// src/lib/mcp/tools/get-employee.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^4.5.4";
var get_employee_default = defineTool2({
  name: "get_employee",
  title: "Get employee details",
  description: "Fetch one employee card with the assets currently assigned to them. Accepts an employee id or employee code.",
  inputSchema: {
    employee_id: z2.string().optional().describe("Employee UUID."),
    employee_code: z2.string().optional().describe("Employee code, e.g. EMP-1042.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ employee_id, employee_code }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (!employee_id && !employee_code) return errorResult("\u05D9\u05E9 \u05DC\u05E1\u05E4\u05E7 employee_id \u05D0\u05D5 employee_code");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("employees").select(
      "id, employee_code, full_name, email, phone, department, role, status, start_date, end_date, direct_manager_id, vacation_balance, sick_balance, tracks_attendance, can_remote_punch"
    ).limit(1);
    query = employee_id ? query.eq("id", employee_id) : query.eq("employee_code", employee_code);
    const { data, error } = await query.maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("\u05D4\u05E2\u05D5\u05D1\u05D3 \u05DC\u05D0 \u05E0\u05DE\u05E6\u05D0 \u05D0\u05D5 \u05E9\u05D0\u05D9\u05DF \u05D4\u05E8\u05E9\u05D0\u05D4 \u05DC\u05E6\u05E4\u05D5\u05EA \u05D1\u05D5");
    const { data: assets } = await supabase.from("assets").select("id, asset_code, asset_name, status, condition, license_plate, serial_number, account_username").eq("current_owner_id", data.id);
    return jsonResult({ employee: data, assigned_assets: assets ?? [] });
  }
});

// src/lib/mcp/tools/list-assets.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^4.5.4";
var list_assets_default = defineTool3({
  name: "list_assets",
  title: "List assets",
  description: "List company resources (equipment, vehicles, digital access, licenses) with optional search, status filter and assignment filter.",
  inputSchema: {
    search: z3.string().optional().describe("Free text matched against asset name, code, serial number or license plate."),
    status: z3.string().optional().describe("Asset status value, e.g. available, assigned, maintenance."),
    unassigned_only: z3.boolean().optional().describe("Return only assets with no current owner."),
    owner_employee_id: z3.string().optional().describe("Return only assets held by this employee UUID."),
    limit: z3.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, unassigned_only, owner_employee_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("assets").select(
      "id, asset_code, asset_name, status, condition, category_id, current_owner_id, manufacturer_model, serial_number, license_plate, account_username, expiry_date, notes"
    ).order("asset_name", { ascending: true }).limit(take);
    if (status) query = query.eq("status", status);
    if (unassigned_only) query = query.is("current_owner_id", null);
    if (owner_employee_id) query = query.eq("current_owner_id", owner_employee_id);
    if (search?.trim()) {
      const term = `%${search.trim()}%`;
      query = query.or(
        `asset_name.ilike.${term},asset_code.ilike.${term},serial_number.ilike.${term},license_plate.ilike.${term}`
      );
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, assets: data ?? [] });
  }
});

// src/lib/mcp/tools/list-leave-requests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^4.5.4";
var list_leave_requests_default = defineTool4({
  name: "list_leave_requests",
  title: "List leave and sickness requests",
  description: "List leave, sickness and reserve-duty requests, optionally filtered by employee, status, type or date range.",
  inputSchema: {
    employee_id: z4.string().optional().describe("Filter by employee UUID."),
    status: z4.string().optional().describe("Request status, e.g. approved, pending, rejected."),
    request_type: z4.string().optional().describe("Request type, e.g. vacation, sick, reserve."),
    from_date: z4.string().optional().describe("Only requests starting on or after this ISO date (YYYY-MM-DD)."),
    to_date: z4.string().optional().describe("Only requests starting on or before this ISO date (YYYY-MM-DD)."),
    limit: z4.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ employee_id, status, request_type, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("leave_requests").select(
      "id, employee_id, request_type, status, start_date, end_date, total_days, reason, manager_note, created_at"
    ).order("start_date", { ascending: false }).limit(take);
    if (employee_id) query = query.eq("employee_id", employee_id);
    if (status) query = query.eq("status", status);
    if (request_type) query = query.eq("request_type", request_type);
    if (from_date) query = query.gte("start_date", from_date);
    if (to_date) query = query.lte("start_date", to_date);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, requests: data ?? [] });
  }
});

// src/lib/mcp/tools/list-it-tickets.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z5 } from "npm:zod@^4.5.4";
var list_it_tickets_default = defineTool5({
  name: "list_it_tickets",
  title: "List IT tickets",
  description: "List IT/operations tickets, optionally filtered by status, priority or employee.",
  inputSchema: {
    status: z5.string().optional().describe("Ticket status, e.g. open, in_progress, resolved."),
    priority: z5.string().optional().describe("Ticket priority, e.g. low, medium, high, urgent."),
    employee_id: z5.string().optional().describe("Filter by requesting employee UUID."),
    limit: z5.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, priority, employee_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("it_tickets").select("id, ticket_code, title, ticket_type, status, priority, employee_id, assigned_to, sla_deadline, created_at, resolved_at").order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    if (priority) query = query.eq("priority", priority);
    if (employee_id) query = query.eq("employee_id", employee_id);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, tickets: data ?? [] });
  }
});

// src/lib/mcp/tools/create-it-ticket.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z6 } from "npm:zod@^4.5.4";
var create_it_ticket_default = defineTool6({
  name: "create_it_ticket",
  title: "Create IT ticket",
  description: "Open a new IT/operations ticket for an employee in \u05EA\u05E4\u05E2\u05D5\u05DC 360.",
  inputSchema: {
    employee_id: z6.string().describe("UUID of the employee the ticket is opened for."),
    title: z6.string().describe("Short ticket title in Hebrew or English."),
    ticket_type: z6.string().optional().describe("Ticket type, e.g. hardware, software, access."),
    priority: z6.string().optional().describe("Priority: low, medium, high or urgent. Defaults to medium.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ employee_id, title, ticket_type, priority }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const trimmed = title.trim();
    if (!trimmed) return errorResult("\u05DB\u05D5\u05EA\u05E8\u05EA \u05D4\u05E7\u05E8\u05D9\u05D0\u05D4 \u05E0\u05D3\u05E8\u05E9\u05EA");
    const supabase = supabaseForUser(ctx);
    const { data: employee, error: employeeError } = await supabase.from("employees").select("id, company_id").eq("id", employee_id).maybeSingle();
    if (employeeError) return errorResult(employeeError.message);
    if (!employee) return errorResult("\u05D4\u05E2\u05D5\u05D1\u05D3 \u05DC\u05D0 \u05E0\u05DE\u05E6\u05D0 \u05D0\u05D5 \u05E9\u05D0\u05D9\u05DF \u05D4\u05E8\u05E9\u05D0\u05D4");
    const { data, error } = await supabase.from("it_tickets").insert({
      employee_id: employee.id,
      company_id: employee.company_id,
      title: trimmed,
      ticket_code: `MCP-${Date.now().toString(36).toUpperCase()}`,
      ...ticket_type ? { ticket_type } : {},
      ...priority ? { priority } : {}
    }).select("id, ticket_code, title, status, priority, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult({ ticket: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "rhzmhiknbcipucfvgkok";
var mcp_default = defineMcp({
  name: "360",
  title: "\u05EA\u05E4\u05E2\u05D5\u05DC 360",
  version: "0.1.0",
  instructions: "\u05DB\u05DC\u05D9\u05DD \u05DC\u05DE\u05E2\u05E8\u05DB\u05EA \u05EA\u05E4\u05E2\u05D5\u05DC 360 (\u05E0\u05D9\u05D4\u05D5\u05DC \u05E2\u05D5\u05D1\u05D3\u05D9\u05DD, \u05DE\u05E9\u05D0\u05D1\u05D9\u05DD, \u05D7\u05D5\u05E4\u05E9\u05D5\u05EA \u05D5\u05E7\u05E8\u05D9\u05D0\u05D5\u05EA \u05E9\u05D9\u05E8\u05D5\u05EA). \u05DB\u05DC \u05D4\u05DB\u05DC\u05D9\u05DD \u05E4\u05D5\u05E2\u05DC\u05D9\u05DD \u05D1\u05D4\u05E8\u05E9\u05D0\u05D5\u05EA \u05D4\u05DE\u05E9\u05EA\u05DE\u05E9 \u05D4\u05DE\u05D7\u05D5\u05D1\u05E8.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_employees_default, get_employee_default, list_assets_default, list_leave_requests_default, list_it_tickets_default, create_it_ticket_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
